Exception: filename added. Runtime:  - Bugfix [20110227] The Current line number is no longer tracked explicitly but extracted from the current statement. This should be more robust.  - Bugfix [20110328] Function calls' initial phase was executed using the wrong context  - ...
git-svn-id: https://svn.berlios.de/svnroot/repos/escript/branches/0.5.3.experimental@39 5693b1fc-3b75-4070-9b6b-3ce3692a40d5